on:
  push:
    branches:
    - main
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04
    steps: 
     - name: Setup Go environment
       uses: actions/setup-go@v4.0.0
       shell:
        - echo "hello"
