on:
  workflow_call:
    inputs:
      image_name:
        type: string
      tag: 
        type: string
   


jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-latest
    steps: 
     -  run: echo "hello child2"
        name: child2 job
