on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      image_name:
        type: string
      tag: 
        type: string
   


jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04
    steps: 
     - name: Setup Go environment
       uses: actions/setup-go@v4.0.0
     -  run: echo "hello"
        name: xxxx
