on:
  workflow_call:
    inputs:
      image_name:
        type: string
      tag: 
        type: string
   


jobs:
  child_job:
    name: deploy to staging
    runs-on: ubuntu-latest
    steps: 
     -  run: echo "hello"
        name: child1
  child_job1:
    uses:  yuantongkang/auto-green/.github/workflows/child2.yml@main 
